window.localVideoLibrary = {
  "pukang-infoflow": [
    {
      "title": "主推案例",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "120.5 MB",
      "size": "120.5 MB",
      "sizeMb": 120.5,
      "url": "assets/videos/pukang-infoflow/01-主推案例.mp4",
      "sourcePath": "assets/videos/pukang-infoflow/01-主推案例.mp4",
      "sourceRelativePath": "assets/videos/pukang-infoflow/01-主推案例.mp4",
      "cover": "assets/covers/cover-01.png",
      "poster": "assets/posters/pukang-infoflow/01-主推案例.jpg"
    },
    {
      "title": "混剪种草",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "70.5 MB",
      "size": "70.5 MB",
      "sizeMb": 70.5,
      "url": "assets/videos/pukang-infoflow/02-混剪种草.mp4",
      "sourcePath": "assets/videos/pukang-infoflow/02-混剪种草.mp4",
      "sourceRelativePath": "assets/videos/pukang-infoflow/02-混剪种草.mp4",
      "cover": "assets/covers/cover-01.png",
      "poster": "assets/posters/pukang-infoflow/02-混剪种草.jpg"
    },
    {
      "title": "大字报",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "1.1 MB",
      "size": "1.1 MB",
      "sizeMb": 1.1,
      "url": "assets/videos/pukang-infoflow/03-大字报.mp4",
      "sourcePath": "assets/videos/pukang-infoflow/03-大字报.mp4",
      "sourceRelativePath": "assets/videos/pukang-infoflow/03-大字报.mp4",
      "cover": "assets/covers/cover-01.png",
      "poster": "assets/posters/pukang-infoflow/03-大字报.jpg"
    },
    {
      "title": "创意宣传",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "46.2 MB",
      "size": "46.2 MB",
      "sizeMb": 46.2,
      "url": "assets/videos/pukang-infoflow/04-创意宣传.mp4",
      "sourcePath": "assets/videos/pukang-infoflow/04-创意宣传.mp4",
      "sourceRelativePath": "assets/videos/pukang-infoflow/04-创意宣传.mp4",
      "cover": "assets/covers/cover-01.png",
      "poster": "assets/posters/pukang-infoflow/04-创意宣传.jpg"
    }
  ],
  "doctor-ip": [
    {
      "title": "主推案例",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "2.0 MB",
      "size": "2.0 MB",
      "sizeMb": 2,
      "url": "assets/videos/doctor-ip/01-主推案例.mp4",
      "sourcePath": "assets/videos/doctor-ip/01-主推案例.mp4",
      "sourceRelativePath": "assets/videos/doctor-ip/01-主推案例.mp4",
      "cover": "assets/covers/cover-02.png",
      "poster": "assets/posters/doctor-ip/01-主推案例.jpg"
    },
    {
      "title": "科普口播",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "4.8 MB",
      "size": "4.8 MB",
      "sizeMb": 4.8,
      "url": "assets/videos/doctor-ip/02-科普口播.mp4",
      "sourcePath": "assets/videos/doctor-ip/02-科普口播.mp4",
      "sourceRelativePath": "assets/videos/doctor-ip/02-科普口播.mp4",
      "cover": "assets/covers/cover-02.png",
      "poster": "assets/posters/doctor-ip/02-科普口播.jpg"
    },
    {
      "title": "科普演绎",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "2.5 MB",
      "size": "2.5 MB",
      "sizeMb": 2.5,
      "url": "assets/videos/doctor-ip/03-科普演绎.mp4",
      "sourcePath": "assets/videos/doctor-ip/03-科普演绎.mp4",
      "sourceRelativePath": "assets/videos/doctor-ip/03-科普演绎.mp4",
      "cover": "assets/covers/cover-02.png",
      "poster": "assets/posters/doctor-ip/03-科普演绎.jpg"
    },
    {
      "title": "综艺感科普",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "3.0 MB",
      "size": "3.0 MB",
      "sizeMb": 3,
      "url": "assets/videos/doctor-ip/04-综艺感科普.mp4",
      "sourcePath": "assets/videos/doctor-ip/04-综艺感科普.mp4",
      "sourceRelativePath": "assets/videos/doctor-ip/04-综艺感科普.mp4",
      "cover": "assets/covers/cover-02.png",
      "poster": "assets/posters/doctor-ip/04-综艺感科普.jpg"
    }
  ],
  "laofengxiang": [
    {
      "title": "主推案例",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.5 MB",
      "size": "0.5 MB",
      "sizeMb": 0.5,
      "url": "assets/videos/laofengxiang/01-主推案例.mp4",
      "sourcePath": "assets/videos/laofengxiang/01-主推案例.mp4",
      "sourceRelativePath": "assets/videos/laofengxiang/01-主推案例.mp4",
      "cover": "assets/covers/cover-03.png",
      "poster": "assets/posters/laofengxiang/01-主推案例.jpg"
    },
    {
      "title": "佩戴展示",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.4 MB",
      "size": "0.4 MB",
      "sizeMb": 0.4,
      "url": "assets/videos/laofengxiang/02-佩戴展示.mp4",
      "sourcePath": "assets/videos/laofengxiang/02-佩戴展示.mp4",
      "sourceRelativePath": "assets/videos/laofengxiang/02-佩戴展示.mp4",
      "cover": "assets/covers/cover-03.png",
      "poster": "assets/posters/laofengxiang/02-佩戴展示.jpg"
    },
    {
      "title": "口播种草",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.7 MB",
      "size": "0.7 MB",
      "sizeMb": 0.7,
      "url": "assets/videos/laofengxiang/03-口播种草.mp4",
      "sourcePath": "assets/videos/laofengxiang/03-口播种草.mp4",
      "sourceRelativePath": "assets/videos/laofengxiang/03-口播种草.mp4",
      "cover": "assets/covers/cover-03.png",
      "poster": "assets/posters/laofengxiang/03-口播种草.jpg"
    },
    {
      "title": "种草混剪",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.8 MB",
      "size": "0.8 MB",
      "sizeMb": 0.8,
      "url": "assets/videos/laofengxiang/04-种草混剪.mp4",
      "sourcePath": "assets/videos/laofengxiang/04-种草混剪.mp4",
      "sourceRelativePath": "assets/videos/laofengxiang/04-种草混剪.mp4",
      "cover": "assets/covers/cover-03.png",
      "poster": "assets/posters/laofengxiang/04-种草混剪.jpg"
    }
  ],
  "ruanshi": [
    {
      "title": "主推案例",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.7 MB",
      "size": "0.7 MB",
      "sizeMb": 0.7,
      "url": "assets/videos/ruanshi/01-主推案例.mp4",
      "sourcePath": "assets/videos/ruanshi/01-主推案例.mp4",
      "sourceRelativePath": "assets/videos/ruanshi/01-主推案例.mp4",
      "cover": "assets/covers/cover-04.png",
      "poster": "assets/posters/ruanshi/01-主推案例.jpg"
    },
    {
      "title": "产品展示",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.6 MB",
      "size": "0.6 MB",
      "sizeMb": 0.6,
      "url": "assets/videos/ruanshi/02-产品展示.mp4",
      "sourcePath": "assets/videos/ruanshi/02-产品展示.mp4",
      "sourceRelativePath": "assets/videos/ruanshi/02-产品展示.mp4",
      "cover": "assets/covers/cover-04.png",
      "poster": "assets/posters/ruanshi/02-产品展示.jpg"
    },
    {
      "title": "佩戴展示",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.6 MB",
      "size": "0.6 MB",
      "sizeMb": 0.6,
      "url": "assets/videos/ruanshi/03-佩戴展示.mp4",
      "sourcePath": "assets/videos/ruanshi/03-佩戴展示.mp4",
      "sourceRelativePath": "assets/videos/ruanshi/03-佩戴展示.mp4",
      "cover": "assets/covers/cover-04.png",
      "poster": "assets/posters/ruanshi/03-佩戴展示.jpg"
    },
    {
      "title": "场景展示",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "0.3 MB",
      "size": "0.3 MB",
      "sizeMb": 0.3,
      "url": "assets/videos/ruanshi/04-场景展示.mp4",
      "sourcePath": "assets/videos/ruanshi/04-场景展示.mp4",
      "sourceRelativePath": "assets/videos/ruanshi/04-场景展示.mp4",
      "cover": "assets/covers/cover-04.png",
      "poster": "assets/posters/ruanshi/04-场景展示.jpg"
    }
  ],
  "wuling": [
    {
      "title": "主推案例",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "1.0 MB",
      "size": "1.0 MB",
      "sizeMb": 1,
      "url": "assets/videos/wuling/01-主推案例.mp4",
      "sourcePath": "assets/videos/wuling/01-主推案例.mp4",
      "sourceRelativePath": "assets/videos/wuling/01-主推案例.mp4",
      "cover": "assets/covers/cover-05.png",
      "poster": "assets/posters/wuling/01-主推案例.jpg"
    },
    {
      "title": "新品宣传",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "4.1 MB",
      "size": "4.1 MB",
      "sizeMb": 4.1,
      "url": "assets/videos/wuling/02-新品宣传.mp4",
      "sourcePath": "assets/videos/wuling/02-新品宣传.mp4",
      "sourceRelativePath": "assets/videos/wuling/02-新品宣传.mp4",
      "cover": "assets/covers/cover-05.png",
      "poster": "assets/posters/wuling/02-新品宣传.jpg"
    },
    {
      "title": "活动混剪",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "8.1 MB",
      "size": "8.1 MB",
      "sizeMb": 8.1,
      "url": "assets/videos/wuling/03-活动混剪.mp4",
      "sourcePath": "assets/videos/wuling/03-活动混剪.mp4",
      "sourceRelativePath": "assets/videos/wuling/03-活动混剪.mp4",
      "cover": "assets/covers/cover-05.png",
      "poster": "assets/posters/wuling/03-活动混剪.jpg"
    },
    {
      "title": "口播种草",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "2.7 MB",
      "size": "2.7 MB",
      "sizeMb": 2.7,
      "url": "assets/videos/wuling/04-口播种草.mp4",
      "sourcePath": "assets/videos/wuling/04-口播种草.mp4",
      "sourceRelativePath": "assets/videos/wuling/04-口播种草.mp4",
      "cover": "assets/covers/cover-05.png",
      "poster": "assets/posters/wuling/04-口播种草.jpg"
    }
  ],
  "saber-tooth": [
    {
      "title": "主推案例",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "4.1 MB",
      "size": "4.1 MB",
      "sizeMb": 4.1,
      "url": "assets/videos/saber-tooth/01-主推案例.mp4",
      "sourcePath": "assets/videos/saber-tooth/01-主推案例.mp4",
      "sourceRelativePath": "assets/videos/saber-tooth/01-主推案例.mp4",
      "cover": "assets/covers/cover-06.png",
      "poster": "assets/posters/saber-tooth/01-主推案例.jpg"
    },
    {
      "title": "活动记录",
      "type": "精选案例",
      "format": "竖屏",
      "duration": "19.6 MB",
      "size": "19.6 MB",
      "sizeMb": 19.6,
      "url": "assets/videos/saber-tooth/02-活动记录.mp4",
      "sourcePath": "assets/videos/saber-tooth/02-活动记录.mp4",
      "sourceRelativePath": "assets/videos/saber-tooth/02-活动记录.mp4",
      "cover": "assets/covers/cover-06.png",
      "poster": "assets/posters/saber-tooth/02-活动记录.jpg"
    }
  ],
  "ai-video": [
    {
      "title": "AI大疆产品场景展示",
      "type": "AI 视频实验",
      "format": "竖屏",
      "duration": "49.5 MB",
      "size": "49.5 MB",
      "sizeMb": 49.5,
      "url": "assets/videos/ai-video/01-AI大疆产品场景展示.mp4",
      "sourcePath": "assets/videos/ai-video/01-AI大疆产品场景展示.mp4",
      "sourceRelativePath": "assets/videos/ai-video/01-AI大疆产品场景展示.mp4",
      "cover": "assets/posters/ai-video/01-AI大疆产品场景展示.jpg",
      "poster": "assets/posters/ai-video/01-AI大疆产品场景展示.jpg"
    },
    {
      "title": "AI大疆运动场景广告",
      "type": "AI 视频实验",
      "format": "竖屏",
      "duration": "16.7 MB",
      "size": "16.7 MB",
      "sizeMb": 16.7,
      "url": "assets/videos/ai-video/02-AI大疆运动场景广告.mp4",
      "sourcePath": "assets/videos/ai-video/02-AI大疆运动场景广告.mp4",
      "sourceRelativePath": "assets/videos/ai-video/02-AI大疆运动场景广告.mp4",
      "cover": "assets/posters/ai-video/02-AI大疆运动场景广告.jpg",
      "poster": "assets/posters/ai-video/02-AI大疆运动场景广告.jpg"
    },
    {
      "title": "AI大疆产品创意短片",
      "type": "AI 视频实验",
      "format": "竖屏",
      "duration": "21.1 MB",
      "size": "21.1 MB",
      "sizeMb": 21.1,
      "url": "assets/videos/ai-video/03-AI大疆产品创意短片.mp4",
      "sourcePath": "assets/videos/ai-video/03-AI大疆产品创意短片.mp4",
      "sourceRelativePath": "assets/videos/ai-video/03-AI大疆产品创意短片.mp4",
      "cover": "assets/posters/ai-video/03-AI大疆产品创意短片.jpg",
      "poster": "assets/posters/ai-video/03-AI大疆产品创意短片.jpg"
    }
  ]
};
